export const animalList = [
	{ name: 'Gorilla', synonyms: ['black gorilla', 'gorilla', 'silverback', 'mountain gorilla', 'Gorilla', 'Berggorilla'] },
	{ name: 'Zebra', synonyms: ['zebra', 'striped horse', 'plains zebra', 'mountain zebra', 'Zebra', 'Steppenzebra'] },
	{ name: 'Elefant', synonyms: ['elephant', 'african elephant', 'ele', 'jumbo', 'bush elephant', 'Elefant', 'Afrikanischer Elefant'] },
	{ name: 'Tiger', synonyms: ['tiger', 'bengal tiger', 'siberian tiger', 'big cat', 'royal tiger', 'Tiger', 'Bengaltiger'] },
	{ name: 'Löwe', synonyms: ['lion', 'african lion', 'male lion', 'lioness', 'king of beasts', 'Löwe', 'Afrikanischer Löwe'] },
	{ name: 'Giraffe', synonyms: ['giraffe', 'reticulated giraffe', 'masai giraffe', 'tall one', 'Giraffe', 'Netzgiraffe'] },
	{ name: 'Pinguin', synonyms: ['penguin', 'emperor penguin', 'king penguin', 'adelie', 'Pinguin', 'Kaiserpinguin'] },
	{ name: 'Panda', synonyms: ['giant panda', 'panda bear', 'bamboo bear', 'great panda', 'Panda', 'Großer Panda'] },
	{ name: 'Koala', synonyms: ['koala', 'koala bear', 'native bear', 'tree bear', 'Koala', 'Koalabär'] },
	{ name: 'Känguru', synonyms: ['kangaroo', 'red kangaroo', 'roo', 'giant kangaroo', 'kanga', 'Känguru', 'Rotes Känguru'] },
	{ name: 'Delfin', synonyms: ['dolphin', 'bottlenose dolphin', 'flipper', 'common dolphin', 'Delfin', 'Großer Tümmler'] },
	{ name: 'Nilpferd', synonyms: ['hippo', 'hippopotamus', 'river horse', 'water horse', 'Nilpferd', 'Flusspferd'] },
	{ name: 'Krokodil', synonyms: ['crocodile', 'nile crocodile', 'croc', 'saltwater crocodile', 'Krokodil', 'Nilkrokodil'] },
	{ name: 'Nashorn', synonyms: ['rhino', 'rhinoceros', 'white rhino', 'black rhino', 'Nashorn', 'Weißes Nashorn'] },
	{ name: 'Papagei', synonyms: ['parrot', 'macaw', 'ara', 'amazon parrot', 'parakeet', 'Papagei', 'Ara'] },
	{ name: 'Eisbär', synonyms: ['polar bear', 'ice bear', 'white bear', 'arctic bear', 'Eisbär', 'Polarbär'] },
	{ name: 'Gepard', synonyms: ['cheetah', 'hunting leopard', 'spotted speedster', 'acinonyx', 'Gepard', 'Jagdleopard'] },
	{ name: 'Flamingo', synonyms: ['flamingo', 'pink flamingo', 'greater flamingo', 'american flamingo', 'Flamingo', 'Rosaflamingo'] },
	{ name: 'Faultier', synonyms: ['sloth', 'three-toed sloth', 'two-toed sloth', 'tree sloth', 'Faultier', 'Dreifingerfaultier'] },
	{ name: 'Otter', synonyms: ['otter', 'sea otter', 'river otter', 'eurasian otter', 'Otter', 'Seeotter'] },
	{ name: 'Erdmännchen', synonyms: ['meerkat', 'suricate', 'desert fox', 'mongoose', 'Erdmännchen', 'Surikate'] },
	{ name: 'Tapir', synonyms: ['tapir', 'malayan tapir', 'mountain cow', 'forest cow', 'Tapir', 'Malaiischer Tapir'] },
	{ name: 'Jaguar', synonyms: ['jaguar', 'black jaguar', 'spotted jaguar', 'american leopard', 'Jaguar', 'Amerikanischer Leopard'] },
	{ name: 'Orang-Utan', synonyms: ['orangutan', 'orange ape', 'orang', 'red ape', 'Orang-Utan', 'Orang'] },
	{ name: 'Seelöwe', synonyms: ['sea lion', 'eared seal', 'stellar sea lion', 'california sea lion', 'Seelöwe', 'Kalifornischer Seelöwe'] },
	{ name: 'Wolf', synonyms: ['wolf', 'gray wolf', 'timber wolf', 'canis lupus', 'Wolf', 'Grauwolf'] },
	{ name: 'Fuchs', synonyms: ['fox', 'red fox', 'vulpes vulpes', 'Fuchs', 'Rotfuchs'] },
	{ name: 'Bär', synonyms: ['bear', 'brown bear', 'grizzly bear', 'ursus arctos', 'Bär', 'Braunbär'] },
	{ name: 'Adler', synonyms: ['eagle', 'bald eagle', 'golden eagle', 'Aquila', 'Adler', 'Steinadler'] },
	{ name: 'Schlange', synonyms: ['snake', 'python', 'cobra', 'viper', 'Schlange', 'Python'] },
	{ name: 'Adler', synonyms: ['eagle', 'bald eagle', 'golden eagle', 'Aquila', 'Adler', 'Steinadler'] },
	{ name: 'Schwan', synonyms: ['swan', 'mute swan', 'whooper swan', 'trumpeter swan', 'Schwan', 'Höckerschwan'] },
	{ name: 'Pfau', synonyms: ['peacock', 'indian peafowl', 'blue peafowl', 'Peafowl', 'Pfau', 'Indischer Pfau'] },
	{ name: 'Storch', synonyms: ['stork', 'white stork', 'black stork', 'Storch', 'Weißstorch'] },
	{ name: 'Rabe', synonyms: ['raven', 'common raven', 'northern raven', 'Rabe', 'Kolkrabe'] },
	{ name: 'Eule', synonyms: ['owl', 'barn owl', 'snowy owl', 'Eule', 'Schneeeule'] },
	{ name: 'Falken', synonyms: ['falcon', 'peregrine falcon', 'Falco', 'Falken', 'Wanderfalke'] },
	{ name: 'Igel', synonyms: ['hedgehog', 'european hedgehog', 'Erinaceus', 'Igel', 'Europäischer Igel'] },
	{ name: 'Dachs', synonyms: ['badger', 'european badger', 'Meles', 'Dachs', 'Europäischer Dachs'] },
	{ name: 'Luchs', synonyms: ['lynx', 'eurasian lynx', 'Lynx', 'Luchs', 'Eurasischer Luchs'] },
	{ name: 'Marder', synonyms: ['marten', 'pine marten', 'Martes', 'Marder', 'Baummarder'] },
	{ name: 'Waschbär', synonyms: ['raccoon', 'common raccoon', 'Procyon', 'Waschbär', 'Nordamerikanischer Waschbär'] },
	{ name: 'Stachelschwein', synonyms: ['porcupine', 'african porcupine', 'Hystrix', 'Stachelschwein', 'Afrikanisches Stachelschwein'] },
	{ name: 'Wiesel', synonyms: ['weasel', 'least weasel', 'Mustela', 'Wiesel', 'Mauswiesel'] },
	{ name: 'Schaf', synonyms: ['sheep', 'domestic sheep', 'Ovis', 'Schaf', 'Hausschaf'] },
	{ name: 'Ziege', synonyms: ['goat', 'domestic goat', 'Capra', 'Ziege', 'Hausziege'] },
	{ name: 'Kuh', synonyms: ['cow', 'domestic cow', 'Bos', 'Kuh', 'Hausrind'] },
	{ name: 'Pferd', synonyms: ['horse', 'domestic horse', 'Equus', 'Pferd', 'Hauspferd'] },
	{ name: 'Huhn', synonyms: ['chicken', 'domestic chicken', 'Gallus', 'Huhn', 'Haushuhn'] },
	{ name: 'Ente', synonyms: ['duck', 'domestic duck', 'Anas', 'Ente', 'Stockente'] },
	{ name: 'Gans', synonyms: ['goose', 'domestic goose', 'Anser', 'Gans', 'Hausgans'] },
	{ name: 'Truthahn', synonyms: ['turkey', 'domestic turkey', 'Meleagris', 'Truthahn', 'Haustruthahn'] }
];

// rekorde im tiere
// kontext und zielgruppe
// nutzergruppe wie schulklasse 4 bspw. oder kinder
