export const animalList = [
    { name: "Gorilla", synonyms: ["black gorilla", "gorilla", "silverback", "mountain gorilla"] },
    { name: "Zebra", synonyms: ["zebra", "striped horse", "plains zebra", "mountain zebra"] },
    { name: "Elefant", synonyms: ["elephant", "african elephant", "ele", "jumbo", "bush elephant"] },
    { name: "Tiger", synonyms: ["tiger", "bengal tiger", "siberian tiger", "big cat", "royal tiger"] },
    { name: "Löwe", synonyms: ["lion", "african lion", "male lion", "lioness", "king of beasts"] },
    { name: "Giraffe", synonyms: ["giraffe", "reticulated giraffe", "masai giraffe", "tall one"] },
    { name: "Pinguin", synonyms: ["penguin", "emperor penguin", "king penguin", "adelie"] },
    { name: "Panda", synonyms: ["giant panda", "panda bear", "bamboo bear", "great panda"] },
    { name: "Koala", synonyms: ["koala", "koala bear", "native bear", "tree bear"] },
    { name: "Känguru", synonyms: ["kangaroo", "red kangaroo", "roo", "giant kangaroo", "kanga"] },
    { name: "Delfin", synonyms: ["dolphin", "bottlenose dolphin", "flipper", "common dolphin"] },
    { name: "Nilpferd", synonyms: ["hippo", "hippopotamus", "river horse", "water horse"] },
    { name: "Krokodil", synonyms: ["crocodile", "nile crocodile", "croc", "saltwater crocodile"] },
    { name: "Nashorn", synonyms: ["rhino", "rhinoceros", "white rhino", "black rhino"] },
    { name: "Papagei", synonyms: ["parrot", "macaw", "ara", "amazon parrot", "parakeet"] },
    { name: "Eisbär", synonyms: ["polar bear", "ice bear", "white bear", "arctic bear"] },
    { name: "Gepard", synonyms: ["cheetah", "hunting leopard", "spotted speedster", "acinonyx"] },
    { name: "Flamingo", synonyms: ["flamingo", "pink flamingo", "greater flamingo", "american flamingo"] },
    { name: "Faultier", synonyms: ["sloth", "three-toed sloth", "two-toed sloth", "tree sloth"] },
    { name: "Otter", synonyms: ["otter", "sea otter", "river otter", "eurasian otter"] },
    { name: "Erdmännchen", synonyms: ["meerkat", "suricate", "desert fox", "mongoose"] },
    { name: "Tapir", synonyms: ["tapir", "malayan tapir", "mountain cow", "forest cow"] },
    { name: "Jaguar", synonyms: ["jaguar", "black jaguar", "spotted jaguar", "american leopard"] },
    { name: "Orang-Utan", synonyms: ["orangutan", "orange ape", "orang", "red ape"] },
    { name: "Seelöwe", synonyms: ["sea lion", "eared seal", "stellar sea lion", "california sea lion"] }
];
